- DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
- crazyara.py
Improved blitz TC with moves left and inc included in the calculation of movetime.
Also supports uci movetime command for fixed time search.
`go movetime 60000`
Tested on blitz TC 10s+0.1s without time forfeit after 140 games.
```
7 CrazyAra 0.2.0 TM        -223 140.0 ( 31.5 : 108.5)
20.0 (  0.0 :  20.0) Stockfish zh 2018-07-25   333
20.0 (  1.5 :  18.5) Imortal v2.0              151
20.0 (  1.5 :  18.5) TJchess 1.3               151
20.0 (  2.5 :  17.5) Sunsetter 9                91
20.0 (  5.0 :  15.0) CrazyWa 1.0.1             -20
20.0 ( 10.0 :  10.0) CrazyAra 0.2.0           -223
20.0 ( 11.0 :   9.0) KKFChess v2.6.6          -261
```
Does not use the rawnet_agent at this TC.
```
1714 >CrazyAra 0.2.0 TM(0): position startpos moves e2e3 d7d5 g1f3 c8g4 f1b5 c7c6 b5e2 e7e6 f3e5 g4e2 d1e2 …
```
> Time control improvements

- DeepCrazyhouse/src/domain/agent/NeuralNetAPI.py
- DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
- DeepCrazyhouse/src/domain/agent/player/RawNetAgent.py
- DeepCrazyhouse/src/domain/agent/player/_Agent.py
- DeepCrazyhouse/src/domain/agent/player/util/NetPredService.py
- DeepCrazyhouse/src/domain/agent/player/util/Node.py
- DeepCrazyhouse/src/domain/crazyhouse/GameState.py
- DeepCrazyhouse/src/domain/neural_net/architectures/Rise.py
- DeepCrazyhouse/src/domain/neural_net/architectures/rise_builder_util.py
- DeepCrazyhouse/src/preprocessing/PGN2PlanesConverter.py
- DeepCrazyhouse/src/preprocessing/PGNRecordDataset.py
- DeepCrazyhouse/src/preprocessing/Planes2RecConverter.py
- DeepCrazyhouse/src/preprocessing/dataset_loader.py
- DeepCrazyhouse/src/preprocessing/pgn_converter_util.py
- DeepCrazyhouse/src/tools/server/game_server.py
- DeepCrazyhouse/src/training/TrainerAgent.py
- crazyara.py
- etc/sf_self_play/sf_cz_game_generator.py
**Import error fixes:**
- Fix everything that prevented the module to be imported f.e `DeepCrazyhouse.configs.main_config` don't exist so I changed to `DeepCrazyhouse.configs.main_config_sample`
**Unused import fixes:**
- Remove every unused module or method
**Wrong import error fixes:**
- The suggested order is - standard modules -> third-party modules -> internal project modules(used isort module to do it)
Test it, it could have caused some minor errors, its rare but happens
Includes reformatting of sf_cz_game_generator.py
> pylint-fixes to everything related to imports

- DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
- DeepCrazyhouse/src/preprocessing/PGNRecordDataset.py
- DeepCrazyhouse/src/preprocessing/pgn_converter_util.py
- DeepCrazyhouse/src/training/TrainerAgent.py
**group similar imports fix**
- It removes redundancy (importing 2 times the same module)
**len-as-condition pylint error fix**
- Making use of truthy value in python, its cleaner and also slightly faster as well since it doesn't call the `len()` function and doesn't make value comparisons
> group similar imports and use truthy values

- DeepCrazyhouse/src/domain/abstract_cls/_GameState.py
- DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
- DeepCrazyhouse/src/preprocessing/PGN2PlanesConverter.py
- DeepCrazyhouse/src/preprocessing/PGNRecordDataset.py
- DeepCrazyhouse/src/preprocessing/Planes2RecConverter.py
- DeepCrazyhouse/src/preprocessing/dataset_loader.py
- DeepCrazyhouse/src/tools/server/game_server.py
- DeepCrazyhouse/src/training/TrainerAgent.py
**fix unreachable code**
- There were 2 unreachable codes due to a `raise notimplementederror()`, I turned them into comments to remove the warning
**fix logging not lazy** 
- It exchanges `%` for `,` Thats preferred because it's lazy. The logging library doesn't format the string at all if the level is not set to DEBUG. That means it doesn't have to do extra work unless the user really wants to see those log messages.
**Exchange scan_headers for read_headers**
- `scan_headers` was removed on python-chess 0.24 version
**Add missing imports(and grouping some others)**
- `DeepCrazyhouse/src/preprocessing/Planes2RecConverter.py` was missing an import
- 2 mxnet module import were separated from each other on the same file
**Remove unused variables or giving use to then**
- …
> Other pylint fixes and some bug fixes

- DeepCrazyhouse/src/domain/agent/NeuralNetAPI.py
- DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
- DeepCrazyhouse/src/domain/agent/player/util/NetPredService.py
- DeepCrazyhouse/src/domain/agent/player/util/Node.py
- DeepCrazyhouse/src/domain/crazyhouse/output_representation.py
- DeepCrazyhouse/src/domain/neural_net/architectures/Rise.py
- DeepCrazyhouse/src/domain/neural_net/architectures/builder_util.py
- DeepCrazyhouse/src/preprocessing/Planes2RecConverter.py
- DeepCrazyhouse/src/tools/visualization/plane_representation.py
**Remove unused modules**
- After the last commit `from mxnet import gluon` is not used anymore
**Remove else-return** 
- No need to use else of elif after a return statement, since if it gets true on the statement from above the function will not even check the else(small cleaning and speed-up)
**Using in instead of 2 or more comparisons**
- Remove repetition for comparisons using the same variable, this is cleaner and it's actually a small speed up
- f.e. `i == nb_res_blocksX_neck - 2 or i == nb_res_blocksX_neck - 1`--> `i in (nb_res_blocksX_neck - 2, nb_res_blocksX_neck - 1)`
**Using` enumerate()` instead of iterating with `range(len(x))`**
- Cleaner and faster as well, no need to use indexation every loop. Only was changed on `DeepCrazyhouse/src/preprocessing/Planes2RecConverter.py` …
> multiple cleaning and very small performance gains

- DeepCrazyhouse/src/domain/neural_net/architectures/rise_builder_util.py
- DeepCrazyhouse/src/preprocessing/PGN2PlanesConverter.py
- DeepCrazyhouse/src/tools/server/game_server.py
- DeepCrazyhouse/src/tools/visualization/plane_representation.py
**Useless object inheritance fix**
-  (Object) call is not necessary on python 3 anymore since classes are children from Object class by default, calling it is redundant and actually is a minor slowdown
**Inconsistent return statements fix** 
- According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)), I don't know the reasoning for it but there must be one since its a PEP8 recommendation, I'll look into it
**Fix bug on plane representation**
- PIECE_VALUES and mult_axis_by_vec weren't being called, now they are
**Remove global(Plz check)**
- I removed a global statement and 1 function that I …
> Multiple cleaning

- DeepCrazyhouse/src/domain/abstract_cls/_GameState.py
- DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
- DeepCrazyhouse/src/domain/agent/player/util/Node.py
- DeepCrazyhouse/src/domain/crazyhouse/GameState.py
- DeepCrazyhouse/src/domain/crazyhouse/output_representation.py
- DeepCrazyhouse/src/domain/neural_net/architectures/Rise.py
- DeepCrazyhouse/src/domain/neural_net/architectures/rise_builder_util.py
- DeepCrazyhouse/src/preprocessing/PGN2PlanesConverter.py
- DeepCrazyhouse/src/preprocessing/Planes2RecConverter.py
- DeepCrazyhouse/src/tools/server/game_server.py
- DeepCrazyhouse/src/training/TrainerAgent.py
**Fix redefined outer name** 
- That happens when a local name identical to a global name. The local name takes precedence, but it hides the global name, makes it inaccessible, and cause confusion to the reader. So I figured it would be better to rename `root` - `local_root`
**Comment out unused arguments**
- Some arguments weren't being used anywhere so I commented them out(maybe there were plans for them, that's why I didn't delete)
**Exchange unused variables for _**
- To make it clear they aren't being used, only applicable on tuple unpacking, otherwise I just deleted it
**Put missing get_pool import from rise_builder_util.py**
- get_pool was missing on the `rise_builder_util.py`
**Fix not-callable**
-  `self.body` was being initialized as None which is not callable, so I followed the …
> multiple small pylint and bug fixes and reformatting 

- DeepCrazyhouse/src/domain/agent/player/Agent.py
- DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
- DeepCrazyhouse/src/domain/agent/player/RawNetAgent.py
- crazyara.py
That's the max cleaning I could do without changing the functionality(hopefully), Hard to list them all but some of them were:
**Remove unrepeated variables on MTCSAgent**
- No need to store values to variables that are used only once
**Remove non-existing parameters from the docstrings `param`**
- There were some references to inexistent parameters
**Turn _Agent class public**
- The class was used on MCTSAgent so it was used outside its own file or children, so it shouldn't be protected(actually I might be wrong here, plz check)
**Multiple typos fixes**
- prioritzes -> prioritizes, among others
**Removing some white lines**
- Mostly to keep the file below 1000 lines
> fixing typos and most of pylint errors originated on MCTSAgent.py

- DeepCrazyhouse/src/tests/full_round_trip_tests.py
- DeepCrazyhouse/src/tests/move_round_trip_test.py
- DeepCrazyhouse/src/training/lr_schedules/lr_schedules.py
- crazyara.py
Focusing on the main file and on files that weren't graded by pylint previously.
**Fixes related to imports**
- Fix wrong import order(standard -> third-party -> local)
- Remove unused modules
- Don't use wildcard imports
**Fix some errors related to naming conventions**
- Module names should use snake case(don't confuse with classes naming which should be CamelCase)
- Unused variables that can't be removed(tuple-unpacking f.e), should become `_`
**Remove repeated method**
- `test_loaded_dataset_white_move` was referenced twice, so the latest wasn't being used, I removed the most incomplete one(plz check - I don't know if I should have just renamed it or which one I should have kept)
**Remove else and elif after returns**
- No need for these checks, since the return statement stops the …
> Several pylint fixes

- DeepCrazyhouse/src/domain/agent/player/mcts_agent.py
Fix a bug that happened at the end of the game (the policy closes crashing the engine since None values don't have `sum` ), this pr handles that crash
> Fix a crashing bug

- engine/CMakeLists.txt
- engine/src/agents/agent.cpp
- engine/src/agents/agent.h
- engine/src/agents/mctsagent.cpp
- engine/src/agents/mctsagent.h
- engine/src/agents/rawnetagent.cpp
- engine/src/agents/rawnetagent.h
- engine/src/board.cpp
- engine/src/board.h
- engine/src/boardstate.cpp
- engine/src/boardstate.h
- engine/src/crazyara.cpp
- engine/src/crazyara.h
- engine/src/domain/crazyhouse/constants.h
- engine/src/domain/crazyhouse/outputrepresentation.cpp
- engine/src/domain/crazyhouse/outputrepresentation.h
- engine/src/evalinfo.cpp
- engine/src/evalinfo.h
- engine/src/manager/treemanager.cpp
- engine/src/manager/treemanager.h
- engine/src/node.cpp
- engine/src/node.h
- engine/src/searchthread.cpp
- engine/src/searchthread.h
- engine/src/state.h
- engine/src/tests/tests.cpp
This PR adds a generic state action interface to allow a convenient integration for non-chess environments (e.g. the [Pommerman environment](https://www.pommerman.com/)).
All environments must implement the interface as described in [state.h](engine/src/state.h).
The interface assumes the environment to be discrete and to define the actions in integer format.
> Generic State Interface

- engine/src/agents/mctsagent.cpp
- engine/src/node.cpp
- engine/src/node.h
- engine/src/searchthread.cpp
- engine/src/state.h
The #ifdef `MCTS_STORE_STATES` allows storing the states within the nodes.
This highly memory consuming but can be beneficial for environments with
a high `do_action()` runtime cost and either low memory consumption or low
total number of nodes in the search tree.
> added MCTS_STORE_STATES

- engine/src/constants.h
- engine/src/node.cpp
- engine/src/searchthread.cpp
- engine/src/searchthread.h
Uses transposition Q-value as target with correction and clamping to avoid divergence.
> Transposition Q-Value Correction

- engine/src/rl/Dockerfile
* updated to [mxnet:20.9-py3](https://docs.nvidia.com/deeplearning/frameworks/mxnet-release-notes/rel_20-09.html#rel_20-09) from mxnet:20.01-py3
* removed MXNet-cpp package dependency
* removed graphviz version information
**Notes:** an even newer MXNet base image was not chosen because there is no current official MXNet release for CUDA 11.2  at the moment and the most update to date with CUDA MXNet version is nightly build with CUDA 11.0 support.
* https://github.com/apache/incubator-mxnet/issues/18657
> Updated Dockerfile

- DeepCrazyhouse/configs/main_config_template.py
- DeepCrazyhouse/configs/train_config_template.py
- DeepCrazyhouse/src/domain/neural_net/architectures/builder_util_symbol.py
- DeepCrazyhouse/src/domain/neural_net/architectures/rise_builder_util.py
- DeepCrazyhouse/src/domain/neural_net/onnx/convert_to_onnx.py
- DeepCrazyhouse/src/domain/util.py
- DeepCrazyhouse/src/training/requirements.txt
- DeepCrazyhouse/src/training/train_cnn.ipynb
- DeepCrazyhouse/src/training/trainer_agent.py
- DeepCrazyhouse/src/training/trainer_agent_mxnet.py
- engine/src/nn/neuralnetapi.cpp
- engine/src/nn/tensorrtapi.cpp
- engine/src/rl/rl_loop.py
- engine/src/rl/rl_training.py
- engine/src/rl/selfplay.cpp
- engine/src/uci/crazyara.cpp
This PR makes training in Gluon the new default since the MXNet Symbol-API will become more and more deprecated (e.g. `SoftmaxOutput()` is not available in MXNet 2.0 anymore (https://github.com/apache/incubator-mxnet/issues/19177)).
> Refactor Training Code and make training in Gluon the new default

- engine/src/agents/mctsagent.cpp
- engine/src/agents/rawnetagent.cpp
- engine/src/environments/chess_related/boardstate.cpp
- engine/src/environments/chess_related/boardstate.h
- engine/src/environments/open_spiel/openspielstate.cpp
- engine/src/environments/open_spiel/openspielstate.h
- engine/src/nn/mxnetapi.cpp
- engine/src/nn/mxnetapi.h
- engine/src/nn/neuralnetapi.h
- engine/src/nn/neuralnetapiuser.cpp
- engine/src/nn/neuralnetapiuser.h
- engine/src/nn/tensorrtapi.cpp
- engine/src/nn/tensorrtapi.h
- engine/src/nn/torchapi.cpp
- engine/src/nn/torchapi.h
- engine/src/node.cpp
- engine/src/node.h
- engine/src/searchthread.cpp
- engine/src/searchthread.h
- engine/src/state.h
- engine/src/stateobj.cpp
- engine/src/stateobj.h
This PR allows defining an optional auxiliary output for the neural network prediction.
It is only enabled for `MCTS_STORE_STATES` for now and `NB_AUXILIARY_OUTPUTS() != 0`.
The auxiliary outputs can be stored in the states in the method `set_auxiliary_outputs(const float* auxiliaryOutputs)`.
> Optional auxiliary outputs for NN prediction

- engine/src/agents/mctsagent.cpp
- engine/src/agents/mctsagent.h
- engine/src/environments/chess_related/boardstate.h
- engine/src/manager/threadmanager.cpp
- engine/src/manager/threadmanager.h
- engine/src/searchthread.cpp
- engine/src/searchthread.h
- engine/src/uci/crazyara.cpp
- engine/src/uci/crazyara.h
This PR allows changing UCI option values after the `isready` command has been given.
:warning: Current limitation: Loading a a different dynamically model by changing `Model_Directory` after `isready` is currently not possible.
> Enable dynamic change of UCI settings after "isready"

- engine/src/util/blazeutil.h
- engine/tests/tests.cpp
This PR fixes **first_and_second_max()** in blazeutil.h and adds a corresponding unit-test.
This fix affects the functionality for `Centi_Q_Value_Weight` > 0.
> Bugfix: first_and_second_max()

- engine/CMakeLists.txt
- engine/src/environments/chess_related/board.cpp
- engine/src/environments/chess_related/board.h
- engine/src/environments/chess_related/boardstate.cpp
- engine/src/environments/chess_related/boardstate.h
- engine/src/environments/open_spiel/openspielstate.cpp
- engine/src/environments/open_spiel/openspielstate.h
- engine/src/rl/selfplay.cpp
- engine/src/state.cpp
- engine/src/state.h
- engine/tests/tests.cpp
- engine/tests/tests.h
This PR adds the following functionality:
* provided check_result() implementation in State.h
* check_result() implementation is not more required in custom environments
+ added unit tests for `State` class
* State: steps_from_null()
* State: Reach terminal state
* State: check_result()
* State: clone()
+ added `ACTION_64_BIT` for environments which require action of 64 bits
+ added virtual `State.init()` which used for unit tests atm, but may later be used in the RL-loop
+ added missing terminal checks for `HORDE`, `RACE`, `KOTH` and `THREECHECK`
> Default implementation for check_result(), unit tests and terminal checks

- engine/src/nn/mxnetapi.cpp
- engine/src/nn/mxnetapi.h
- engine/src/nn/neuralnetapi.cpp
- engine/src/nn/neuralnetapi.h
- engine/src/uci/crazyara.cpp
- engine/src/uci/optionsuci.cpp
This PR enables an automatic parsing of the given model file names based on the UCI option "Precision".
This change only affects the MXNetAPI (CPU / IntelMKL) back-end.
Current precision default is set to int8 for CPU.
A set of int8 model weights is expected to contain the string "int8" to be loaded.
If none of these files have been found, a fallback to float32 weights is performed.
> CPU - INT8: Switch between float32 & int8

- engine/src/agents/config/searchsettings.cpp
- engine/src/agents/config/searchsettings.h
- engine/src/agents/mctsagent.cpp
- engine/src/evalinfo.cpp
- engine/src/evalinfo.h
- engine/src/manager/threadmanager.cpp
- engine/src/node.cpp
- engine/src/node.h
- engine/src/searchthread.cpp
- engine/src/uci/crazyara.cpp
- engine/src/uci/optionsuci.cpp
* added UCI-Option Centi_Q_Veto_Delta (closes #85)
*   Describes how much better the highest Q-Value has to be to replace the candidate move with the highest visit count, default value: 40
* removed unused option Max_Search_Depth
TC: 10s + 0.1s
```python
Score of ClassicAra 0.9.1 - Q-Veto-Delta - 0.4 vs ClassicAra 0.9.0: 17 -
7 - 44 [0.574]
Elo difference: 51.5 +/- 48.9, LOS: 97.9 %, DrawRatio: 64.7 %
68 of 1000 games finished.
```
> Q-Veto-Delta

- engine/src/uci/customlogger.cpp
- engine/src/uci/customlogger.h
- engine/src/uci/optionsuci.cpp
Replaced Logger by customLogger instance (closes #78)
The customLogger class prints all **stdin**, **stdout**, **stderr** to a file.
Its write mode, e.g. **"w"** or **"a"**, can be adjusted.
> customLogger instance

- engine/src/evalinfo.cpp
- engine/src/evalinfo.h
- engine/src/node.cpp
- engine/src/node.h
- engine/src/stateobj.cpp
- engine/src/stateobj.h
Changed variable type of MCTS-Policy to double.
This is to avoid artifacts for more than 16 million visits (#39)
Deleted unused function `mcts_policy_based_on_q_n()`.
---
TC: 10s + 0.1s
```python
Score of ClassicAra 0.9.1 - TB- 3-4-5-wdl vs ClassicAra 0.9.1 - TB- 3-4-5-wdl - prev: 8 - 6 - 26 [0.525]
Elo difference: 17.4 +/- 64.3, LOS: 70.4 %, DrawRatio: 65.0 %
40 of 1000 games finished.
```
> mctsPolicy<double>

- engine/src/environments/chess_related/board.cpp
* disabled `draw_by_insufficient_material()` for King of the Hill, Three Check, Anti-Chess, Racing-Kings.
* modified `draw_by_insufficient_material()` for Horde.
> Draw by insiffucient material for variants

- engine/src/rl/README.md
Simple change to the reinforcement learning `README.md`
* Added a note that the `trainer` gpu has to be started first
* Added a note that there can be at most 1 trainer gpu
* Described from which folders the `rl_loop.py` will load the model
> RL Readme change

- engine/src/constants.h
- engine/src/uci/crazyara.cpp
- engine/src/uci/optionsuci.cpp
- engine/src/uci/variants.h
This PR enables dynamic reload of the neural network if the value for `Model_Directory`, `Threads` or `UCI_Variant` was changed.
* added check for _MultiAra_ that the `Model_Directory` must have the `UCI_Variant` in its file path
* otherwise ther could be a problem of conflicting UCI_Variant and Model_Directory values
> Dynamic NN Reloading

- engine/src/constants.h
- engine/src/uci/crazyara.cpp
- engine/src/uci/crazyara.h
- engine/src/uci/timeoutreadythread.cpp
- engine/src/uci/timeoutreadythread.h
- engine/src/util/killablethread.h
* added TimeOutReadyThread
* Thread which prints out "readyok" after a given amount of ms unless
killed.
* This is to avoid running into time outs of e.g. cutechess on Multi-
GPU systems when deserializing complex NN architectures.
> Time-out readyok thread

- engine/src/constants.h
- engine/src/nn/mxnetapi.h
- engine/src/uci/crazyara.cpp
- engine/src/uci/optionsuci.cpp
* replaced constant TIME_OUT_IS_READY_MS by
UCI option "Timeout_MS"
* default value is 13000
after this time "readyok" will be replied to avoid running in a time-out
* update to engine version 0.9.2.post0
> UCI Option "Timeout_MS"

- engine/src/searchthread.cpp
This PR treats tablebase entry points as terminal nodes
TimeControl "5+0.1"
```python
Score of ClassicAra 0.9.3-Dev - TB - Terminal - 3 Threads vs ClassicAra
0.9.3-Dev -TB - Default - 3 Threads: 50 - 8 - 38 [0.719]
Elo difference: 163.0 +/- 55.9, LOS: 100.0 %, DrawRatio: 39.6 %
96 of 1000 games finished.
```
> Terminal TB nodes

- DeepCrazyhouse/configs/rl_config.py
- DeepCrazyhouse/configs/train_config_template.py
- engine/CMakeLists.txt
- engine/src/environments/chess_related/boardstate.cpp
- engine/src/environments/chess_related/boardstate.h
- engine/src/environments/chess_related/chess960position.h
- engine/src/rl/binaryio.py
- engine/src/rl/fileio.py
- engine/src/rl/rl_loop.py
- engine/src/rl/rl_utils.py
- engine/src/rl/selfplay.cpp
- engine/src/rl/selfplay.h
- engine/src/uci/optionsuci.cpp
- engine/src/uci/optionsuci.h
- engine/src/uci/variants.h
- engine/tests/tests.cpp
- engine/tests/tests.h
- Add `960` support
- Save all training `logs`, not only the most recent training log
- Adding some printouts
- Setting `model_contender_dir` explicitly when using Reinforcement Learning
- Updated `nn_update_index` logic, now it works properly (only trainer gpu needs the parameter now. But you may also pass it to the generator gpu)
- Support for different name of `variants` (e.g. standard/chess, antichess/giveaway, ...)
- Delete `gameIdx` and `gamePGNSelfplay` before starting selfplay (here, we should proabably choose a faster method)
> Chess960 support

- engine/src/rl/traindataexporter.cpp
- engine/src/uci/optionsuci.cpp
- engine/src/util/communication.h
added `info_string_important()` to reduce the number of direct `cout<<` calls.
* messages from `info_string_important` are not disabled by `DISABLE_UCI_INFO`.
> Important info string messages

- engine/src/node.h
- engine/src/searchthread.cpp
This PR fixes a bug in the solver for MCGS when a visit was back-propagated as a transposition value and the MCGS solver was not triggered. This could lead to stalling connection.
This seems also to reduce the search time for forced mates / tb-wins.
e.g. MCGS Solver (updated):
```python
info depth 10 seldepth 14 multipv 1 score mate -5 nodes 699 nps 11459 tbhits 0 time 61 pv b3c4 f3e4 c4b3 e4d3 b3b2 a5a4 b2b1 d3c3 b1c1 a4c2
info string 8/8/8/Q7/8/1k3K2/8/8 b - - 4 82
bestmove b3c4
```
e.g. MCGS Solver (old):
```python
info depth 10 seldepth 14 multipv 1 score mate -5 nodes 875 nps 9943 tbhits 0 time 88 pv b3c4 f3e4 c4b3 e4d3 b3b2 a5a4 b2b1 d3c3 b1c1 a4a1
info string 8/8/8/Q7/8/1k3K2/8/8 b - - 4 82
bestmove b3c4
```
e.g. MCTS Solver:
```python
info depth 10 seldepth 18 multipv 1 score mate …
```
> Bugfix MCGS Solver

- engine/src/node.cpp
- engine/src/node.h
- engine/src/searchthread.cpp
- engine/src/searchthread.h
* refactored get_new_child_to_evaluate(), add_new_node_to_tree(), random_playout()
* remove ugly `nullptr` checks
```python
TC: 3s + 0.1s
Score of ClassicAra 0.9.3-Dev - 6-Men-TB - - 3 Threads vs ClassicAra
0.9.3-Dev -No TB - Default - 3 Threads: 62 - 68 - 174 [0.490]
Elo difference: -6.9 +/- 25.5, LOS: 29.9 %, DrawRatio: 57.2 %
304 of 1000 games finished.
```
Hopefully, 100% stable now.
> Shared pointer graph refactoring

- engine/src/agents/mctsagent.cpp
- engine/src/agents/mctsagent.h
- engine/src/evalinfo.cpp
- engine/src/evalinfo.h
- engine/src/node.cpp
- engine/src/node.h
- engine/src/nodedata.cpp
- engine/src/nodedata.h
- engine/src/searchthread.cpp
- engine/src/searchthread.h
* added reachedTablebases
* added get_value_display()
* added is_loss_node_type(), is_draw_node_type(), is_win_node_type()
* added mcts_policy_based_on_losses()
* fixed prune_losses_in_mcts_policy() for `MCTS_SINGLE_PLAYER`
* disabled drawing actions for winning TBs
```python
3s + 0.1s
Score of ClassicAra 0.9.3-Dev -6-Men-TB - 3 Threads - Reach-TB vs ClassicAra 0.9.3-Dev -6-Men-TB - 3 Threads - Master: 78 - 81 - 258 [0.496]
Elo difference: -2.5 +/- 20.6, LOS: 40.6 %, DrawRatio: 61.9 %
417 of 1000 games finished.
```
> Reached tablebases funtionality

- engine/src/constants.h
- engine/src/searchthread.cpp
replaced TERMINAL_NODE_CACHE by batchSize x 2
```python
TC 7s + 0.1s
Score of CrazyAra 0.9.3 - Release vs CrazyAra 0.9.0 - Release: 99 - 97 -
28 [0.504]
Elo difference: 3.1 +/- 42.7, LOS: 55.7 %, DrawRatio: 12.5 %
224 of 1000 games finished.
```
> Release 0.9.3

- engine/src/uci/optionsuci.cpp
- engine/src/uci/optionsuci.h
**Old behavior:**
* When the binary supports multiple variants, the first variant of the `availableVariants` vector is set as default for the UCI options `UCI_variant` and `Model_Directory`
**New behavior:**
* When the binary is loaded, the default variant is set to the first variant in the `availableVariants` vector that has a model
**Solved problems:**
* When we run the binary, but we do not have a model for the first variant in the `availableVariants` vector, the binary does not crash when `isready` is called
* This way, we don't need to have a model for the first variant in `availableVariants` on our hard drive, if we want to play a different variant
> Setting UCI_Variant and Model_Directory dynamically

- engine/src/uci/optionsuci.cpp
- engine/src/uci/variants.h
- engine/tests/tests.cpp
**Problem:**
* Internally we used the string `giveaway` as representation for the uci variant giveaway/antichess, without adding the `C directive` for giveaway. This way, the variants vector provided by multivariant stockfish did not recognize the variant and always returned the standard values for standard chess.
**Fix:**
* Now we use `antichess` as internal representation, as we have included the antichess directive.
* There is no need to include the `giveaway` directive, because the strings `giveaway` and `losers` get translated to `antichess`
> Fix antichess representation

- DeepCrazyhouse/src/domain/neural_net/architectures/rise_mobile_v3.py
- DeepCrazyhouse/src/domain/util.py
- DeepCrazyhouse/src/domain/variants/classical_chess/v2/input_representation.py
- DeepCrazyhouse/src/domain/variants/constants.py
- DeepCrazyhouse/src/domain/variants/input_representation.py
- DeepCrazyhouse/src/preprocessing/dataset_loader.py
- DeepCrazyhouse/src/tests/full_round_trip_tests.py
- DeepCrazyhouse/src/training/train_cnn.ipynb
This presentation avoids potential overfitting and bias, e.g. no color information, no move counter, no progress counter
and adds features which are hard for the CNN to extract, e.g. material info, number legal moves, checkerboard,
opposite color bishops.
| Feature | Planes | Description |
| --- | --- | --- |
| P1 piece | 6 | (pieces are ordered: PAWN, KNIGHT, BISHOP, ROOK, QUEEN, KING) |
| P2 piece | 6 | (pieces are ordered: PAWN, KNIGHT, BISHOP, ROOK, QUEEN, KING) |
| En-passant square | 1 | (Binary map indicating the square where en-passant capture is possible) |
| P1 castling | 2 | (One if castling is possible, else zero) |
| P2 castling | 2 | (One if castling is possible, else zero) |
| Last Moves | 16 | Trajectory of last 8 moves played |
| is960 | 1 | indicate if 960 is active |
| …
> Chess input representation v2.1

- DeepCrazyhouse/src/domain/neural_net/architectures/mxnet_alpha_zero.py
- DeepCrazyhouse/src/domain/neural_net/architectures/rise_mobile_v2.py
- DeepCrazyhouse/src/domain/neural_net/architectures/rise_mobile_v3.py
- DeepCrazyhouse/src/domain/neural_net/generate_random_nn.py
This PR adds a command-line tool to generate a random initialized neural network and export its MXNet and ONNX weights.
This functionality is useful for e.g. starting RL form zero knowledge.
> Generate random initialized neural network

- DeepCrazyhouse/configs/train_config_template.py
- DeepCrazyhouse/src/domain/neural_net/architectures/builder_util_symbol.py
- DeepCrazyhouse/src/domain/neural_net/architectures/rise_mobile_v3.py
- DeepCrazyhouse/src/training/train_cnn.ipynb
- DeepCrazyhouse/src/training/trainer_agent_mxnet.py
- engine/src/environments/chess_related/boardstate.h
- engine/src/environments/chess_related/inputrepresentation.cpp
This PR adds  Win-Draw-Loss-Plys_to_End (WDLP) Head as well as a seperate WDL and plys to end head.
```python
tc.val_loss_factor = 0.01
tc.policy_loss_factor = 0.988
tc.plys_to_end_loss_factor = 0.002
tc.wdl_loss_factor = 0.01
```
```python
kernels = [3] * 7
se_types = [None] * len(kernels)
se_types[5] = "eca_se"
symbol = rise_mobile_v3_symbol(channels=256, channels_operating_init=224, channel_expansion=32, act_type='relu',
channels_value_head=8, value_fc_size=256,
channels_policy_head=NB_POLICY_MAP_CHANNELS,
grad_scale_value=tc.val_loss_factor,
grad_scale_policy=tc.policy_loss_factor,
grad_scale_wdl=tc.wdl_loss_factor,
grad_scale_ply=tc.plys_to_end_loss_factor,
dropout_rate=tc.dropout_rate, select_policy_from_plane=True,
kernels=kernels, se_types=se_types, use_avg_features=False, …
```
> WDLP value head

- engine/src/evalinfo.cpp
- engine/src/node.cpp
This PR adds shared pointer operations when accessing other shared pointers form the hash table and adding new nodes to the tree as shared pointers are not thread safe.
Stable for 572 games. However, the lower performance with TB should be addressed again.
```python
Score of ClassicAra 0.9.4-Dev -6-Men-TB - 2 Threads - Master vs ClassicAra 0.9.4-Dev - 2 Threads - Master:
142 - 177 - 253 [0.469]
Elo difference: -21.3 +/- 21.3, LOS: 2.5 %, DrawRatio: 44.2 %
572 of 1000 games finished.
```
> Shared pointer atomic operation

- engine/src/constants.h
- engine/src/manager/timemanager.h
This PR updates the constants of the time-management.
```shell
./cutechess-cli -variant standard -openings file="/data/SL/Drawkiller_unbalanced_V4_3mvs_+070_+099.pgn" format=pgn plies=100 -pgnout time_manag.pgn -resign movecount=5 score=600 -draw movenumber=30 movecount=4 score=20 -concurrency 1 -engine name=ClassicAra-0.9.4_Time_Manag option.Threads=3 cmd=./@JC_ClassicAra_time_manag -engine name=ClassicAra-0.9.4_8007fa0 option.Threads=3 cmd=./@JC_ClassicAra_8007fa0 -each dir=/data/SL/ proto=uci tc=0/1:0+0.25 option.First_Device_ID=5 option.Last_Device_ID=5 -games 2 -rounds 300 -repeat&
```
```python
tc=0/1:0+0.25
Name                        :  Games                 Elo    Pts   Pts%   Win  Loss  Draw  Tf  Sc
ClassicAra-0.9.4_8007fa0    :    426   -97.06 +/-  22.94  155.0   36.4    46 …
```
> Update Timemanagement Constants

- engine/src/nn/neuralnetapi.h
- engine/src/nn/tensorrtapi.cpp
- engine/src/nn/tensorrtapi.h
This PR retrieves the neural network indices for the output layers rather than hardcoding them.
Currently only supported in the TensorRT back-end.
* added `retrieve_indices_by_name()` for TensorrtAPI
* added constant layer name to `nnDesign`
> Retrieve neural network indices in TensorrtAPI

- engine/src/rl/binaryio.py
- engine/src/rl/rl_loop.py
* Adds a logging statement with the number of found tablebases
* Changes logging of config files to increase readability
An example logging output is shown on the following image:
> RL Logging: Found tablebases and Configs

- engine/src/rl/binaryio.py
- engine/src/rl/rl_loop.py
* Adds a logging statement with the number of found tablebases
* Changes logging of config files to increase readability
An example logging output is shown on the following image:
> RL Logging: Found tablebases and Configs 2.0

- engine/src/environments/chess_related/inputrepresentation.cpp
- engine/src/environments/chess_related/inputrepresentation.h
- engine/src/environments/chess_related/sfutil.cpp
- engine/src/environments/chess_related/sfutil.h
* speed optimization for get_state_planes()
```C++
float* inputPlanes = new float[StateConstants::NB_VALUES_TOTAL()];
BoardState state;
int it = 100000;
// Get starting timepoint
auto start = high_resolution_clock::now();
for (int i = 0; i < it; ++i) {
state.get_state_planes(false, inputPlanes);
}
// Get ending timepoint
auto stop = high_resolution_clock::now();
// Get duration. Substart timepoints to
// get durarion. To cast it to proper unit
// use duration cast method
auto duration = duration_cast<microseconds>(stop - start);
cout << "Time taken by function: "
<< duration.count() << " microseconds" << endl;
```
* Time taken by function: **37 732 microseconds**
* Time taken by function: **32 311 microseconds**
Speed-up by about **14%**.
> Speed Optimization: get_state_planes()

- engine/src/agents/config/searchlimits.cpp
- engine/src/agents/config/searchlimits.h
- engine/src/agents/mctsagent.cpp
- engine/src/constants.h
- engine/src/evalinfo.cpp
- engine/src/evalinfo.h
- engine/src/manager/threadmanager.cpp
- engine/src/manager/threadmanager.h
- engine/src/manager/timemanager.cpp
- engine/src/manager/timemanager.h
- engine/src/node.cpp
- engine/src/node.h
Refactored time management and fixed bug when losing on time.
Now it is taken into account that increment is applied after the move is done (and not before).
Thanks to AdminX and Werner Schüle for reporting it:
* http://talkchess.com/forum3/viewtopic.php?f=2&t=77020&p=895388&hilit=classicara#p895388
---
```python
./cutechess-cli -variant standard -openings file="/data/SL/opening_suites/UHO_V3_6mvs_+090_+099.pgn" format=pgn plies=100 -pgnout "/data/SL/pgn_out/time_manag_refactor.pgn" -resign movecount=5 score=600 -draw movenumber=30 movecount=4 score=20 -concurrency 1 -engine name=ClassicAra-0.9.5_time_refactor_70e37e5 cmd=/data/SL/@JC_ClassicAra_time_refactor_70e37e5 -engine name=ClassicAra-0.9.5_e17e608_wdlp_input_3.0 cmd=/data/SL/@JC_ClassicAra_input_3.0 -each dir=/data/SL/ …
```
> Time management refactoring & bugfix

- DeepCrazyhouse/src/domain/abstract_cls/abs_game_state.py
- DeepCrazyhouse/src/domain/agent/player/alpha_beta_agent.py
- DeepCrazyhouse/src/domain/agent/player/mcts_agent.py
- DeepCrazyhouse/src/domain/agent/player/raw_net_agent.py
- DeepCrazyhouse/src/domain/variants/game_state.py
- DeepCrazyhouse/src/domain/variants/output_representation.py
- DeepCrazyhouse/src/preprocessing/pgn_converter_util.py
- DeepCrazyhouse/src/tests/full_round_trip_tests.py
- DeepCrazyhouse/src/tests/move_round_trip_test.py
- engine/src/agents/mctsagent.cpp
- engine/src/agents/rawnetagent.cpp
- engine/src/environments/chess_related/boardstate.cpp
- engine/src/environments/chess_related/boardstate.h
- engine/src/node.cpp
- engine/src/node.h
- engine/src/searchthread.cpp
- engine/src/searchthread.h
- engine/src/state.cpp
- engine/src/state.h
This PR allows the state environment to disable the policy.
This can be useful for environments such as racing kings.
Implementation is both available in python as well as C++.
> Mirror policy

- engine/src/rl/fileio.py
- engine/src/rl/rl_loop.py
- engine/src/rl/rl_training.py
**Changes:**
* Removes a `bug`, where the GPU crashed if a spike occurred during training
* The spike could not load the latest model, because no intermediate models where saved during training
* Set `export_weights` in `rl_training.py` to true
* Added function in `fileio` that removes all model files in the weight directory
* Calling the function at the end of training
**TODO:**
* if a spike occures before the first intermediate model is saved, the GPU will still crash. A fix to this is a little more challenging, because the `rl_loop` saves the models in a different format and we cannot reconstruct the file name that the trainer class needs.
> RL: Save intermediate model files and delete them after training

- .github/workflows/cmake_build_tests.yml
Created cmake_build_tests.yml to re-enable CI.
> GitHub Actions / CI

- DeepCrazyhouse/src/domain/variants/game_state.py
- DeepCrazyhouse/src/domain/variants/input_representation.py
- engine/src/environments/chess_related/boardstate.cpp
- engine/src/environments/chess_related/inputrepresentation.cpp
- engine/src/environments/chess_related/inputrepresentation.h
- engine/tests/tests.cpp
* Fixes channel ordering for `flip_board() == False and sideToMove == chess.BLACK` in python code.
* Added 3 unit-tests to ensure that `get_state_planes()` works properly for racing kings.
* `mirror_policy()` now depends on `flip_board()`.
Related PRs: #137, #107
> Fix channel ordering for flip_board() == False

- engine/src/uci/optionsuci.cpp
- engine/src/uci/variants.h
* Change the variant input string to lower case (e.g. `lichess.org` sends capital letters)
* Load new model, when the option `UCI_Chess960` gets changed
* Support the variant string `ThreeCheck` in addition to `3check`
> Variant input changes

- engine/CMakeLists.txt
- engine/src/environments/chess_related/chessbatchstream.cpp
This PR aims to enable TensorRT 8 support. 
* removed `myelin` from `CMakeLists.txt`
* updated `ChessBatchStream::getDims()`
Related issue: #109
> TensorRT 8.0 Compability

- engine/CMakeLists.txt
- engine/src/nn/neuralnetapi.cpp
- engine/src/nn/neuralnetapi.h
Added `read_version_from_string()`
which allows parsing version identifier information based on the model name for different input representations.
It is expected to come after the substring `"-v"` in the format `"-v-<Major>.<Minor>"`, e.g. `"-v1.2.onnx"`.
If the information is missing or parsing failed, `make_version<0,0,0>()` will be returned.
Versioning patch information is always set to 0.
> Input Representation Version Parsing

- engine/src/agents/mctsagent.cpp
- engine/src/agents/mctsagent.h
- engine/src/nn/neuralnetapi.cpp
- engine/src/node.h
Sets evaluation for rootNode in case of only a single legal available move based on the last search evaluation.
This avoids artificats for single moves in case the last tree is not re-used, e.g. reinforcement learning.
> Single Move Evaluation

- engine/src/agents/config/searchsettings.cpp
- engine/src/agents/mctsagent.cpp
- engine/src/constants.h
- engine/src/rl/fileio.py
- engine/src/rl/rl_loop.py
- engine/src/uci/crazyara.cpp
- engine/src/uci/optionsuci.cpp
- engine/src/uci/variants.h
Added binary name as sub-directory in `Model_Directory` and `Model_Directory_Contender`
* this avoids conflicts between different binaries which both support the
same variant (e.g. crazyhouse and chess is supported by MultiAra, and
was already supported by CrazyAra and ClassicAra respectively)
* fixed potential segfault when running "quit"
* set default batch-size in SearchSettings to 8
* increased engine version to 0.9.5
* set default precision for CPU back to float32
* specified engine authors in more detail
* updated `availableVariants` for `MODE_STRATEGO`, `MODE_OPENSPIEL`, `MODE_XIANGQI`
> Include binary name in Model_Directory and miscellaneous

- engine/CMakeLists.txt
- engine/src/agents/mctsagent.cpp
- engine/src/constants.h
- engine/src/nn/neuralnetapi.cpp
- engine/src/nn/neuralnetapi.h
- engine/src/nn/neuralnetdesign.h
- engine/src/nn/openvinoapi.cpp
- engine/src/nn/openvinoapi.h
- engine/src/nn/tensorrtapi.cpp
- engine/src/searchthread.cpp
- engine/src/searchthread.h
- engine/src/uci/crazyara.cpp
This PR provides a compatible interface to use _CrazyAra_ networks in the ONNX format using the [**OpenVino**](https://docs.openvinotoolkit.org) API.
The OpenVino API can be used with CPUs, Intel Neural Compute Sticks and Intel GPUs.
For now only CPUs are supported.
The following environment variable must be set to build using `BACKEND_OPENVINO`:
```bash
OPEN_VINO_PATH=/opt/intel/openvino_2021/
ngraph_DIR=/opt/intel/openvino_2021/deployment_tools/ngraph/cmake/
InferenceEngine_DIR=/opt/intel/openvino_2021/deployment_tools/inference_engine/share
```
:warning: This PR also fixes a bug of applying softmax twice for `isPolicyMap==false`.
> OpenVino Backend

- engine/src/searchthread.cpp
This PR reverts the MCTS condition for filling a single iteration.
```python
Score of CrazyAra 0.9.7 - Dev vs CrazyAra 0.9.7 Master: 144 - 124 - 36
[0.533]
Elo difference: 22.9 +/- 36.8, LOS: 88.9 %, DrawRatio: 11.8 %
304 of 1000 games finished.
```
> MCTS Limit Condition

- engine/src/environments/fairy_state/fairyboard.cpp
- engine/src/environments/fairy_state/fairystate.cpp
- engine/src/uci/crazyara.cpp
* Avoids repeating positions in Xiangqi
* Sets stalemate as lost game
> Avoid repeating positions in Xiangqi (closes #101)

- engine/src/agents/agent.cpp
- engine/src/agents/agent.h
- engine/src/agents/mctsagent.cpp
- engine/src/agents/mctsagent.h
- engine/src/uci/crazyara.cpp
This PR allows handling a high number of go and stop commands within a short time period by using a mutex.
> Handle flooding of UCI-commands (close #81)

- engine/src/node.cpp
- engine/src/node.h
Fixes terminal solver for mode `MCTS_SINGLE_PLAYER`.
Also adds `only_child_nodes_of_one_kind()` to reduce duplicated code.
> Fix terminal solver for MCTS_SINGLE_PLAYER

- DeepCrazyhouse/src/domain/agent/neural_net_api.py
the neural_net_api only selects the first file from the param directory in the main config, now it searches explicitly for a .params file
> fixed params file selection from the main_config for the neural_net_api.py

- engine/src/uci/crazyara.cpp
- engine/src/uci/crazyara.h
Rename the mctsmatch and evaltournament commands so that it is clearer what they do. Removed the mctstournament command since it is basically a smaller version of evaltournament and obsolete.
> Rename mctsmatch and evaltournament

- engine/src/nn/neuralnetapi.cpp
- engine/src/nn/neuralnetapi.h
- engine/src/nn/openvinoapi.cpp
- engine/src/nn/openvinoapi.h
- engine/src/nn/tensorrtapi.cpp
This PR allows dynamic shapes of ONNX models. This avoids storing multiple onnx files for each batch size but with the same network parameters. 
* update TensorrtAPI
* update OpenVinoAPI: (now needs to be openvino_2022.1.0 or higher!)
The required onnx files should use **-1**in the batch-size dimension and no longer have batch-size specifier in its file name, e.g. `model-1.20787-0.581-0535-v3.0.onnx` instead of  `model-1.20787-0.581-0535-v3.0-bsize-64.onnx`.
> Dynamic ONNX shape support

- DeepCrazyhouse/configs/rl_config.py
- engine/src/agents/config/rlsettings.h
- engine/src/rl/selfplay.cpp
- engine/src/rl/selfplay.h
- engine/src/uci/crazyara.cpp
- engine/src/uci/optionsuci.cpp
This PR adds the possibility to set the starting fen position in RL using an epd file.
The file path to the epd file which is by default `<empty>` is set via the uci-option `EPD_File_Path`.
> Fen position from epd file

- DeepCrazyhouse/src/training/requirements.txt
- engine/src/rl/Dockerfile
- engine/src/rl/README.md
- engine/src/rl/rl_training.py
This PR add Dockerfile support for pytorch.
Before building the container, the framework can be chosen via command line arguments.
> Dockerfile Pytorch Support

- engine/src/node.h
This PR aims to fix a bug when losing on time in forced mating sequences.
Example game:
* https://tcec-chess.com/#div=ql&game=102&season=23
Now `solveForTerminal` is kept on `true` when descending from a terminal node.
> MCTS solver bug fix

- engine/src/agents/config/searchsettings.cpp
- engine/src/agents/config/searchsettings.h
- engine/src/agents/mctsagent.cpp
- engine/src/agents/mctsagent.h
- engine/src/agents/mctsagentbatch.cpp
- engine/src/evalinfo.cpp
- engine/src/evalinfo.h
- engine/src/node.cpp
- engine/src/node.h
- engine/src/searchthread.cpp
- engine/src/searchthread.h
- engine/src/uci/crazyara.cpp
- engine/src/uci/optionsuci.cpp
This PR replaces the `#ifdef` flag `MCTS_SINGLE_PLAYER_MODE` with a dynamic search setting called `searchPlayerMode`.
This allows changing the `searchPlayerMode` between two different search runs, i.e. for Pommerman.
The variable can also be set via the UCI-Option `Search_Player_Mode`.
For chess and other two player zero sum games, only `Search_Player_Mode == two_player`, makes sense.
> Dynamic single player search

- engine/tests/tests.cpp
This PR replaces the deprecated Approx() floating point comparison by Catch::Matchers::WithinRel().
* https://github.com/catchorg/Catch2/blob/devel/docs/comparing-floating-point-numbers.md#comparing-floating-point-numbers-with-catch2
> Replace deprecated Approx() by Catch::Matchers::WithinRel()

- engine/src/agents/agent.cpp
- engine/src/agents/agent.h
- engine/src/agents/config/searchlimits.cpp
- engine/src/agents/mctsagent.cpp
- engine/src/agents/mctsagentbatch.cpp
- engine/src/agents/rawnetagent.cpp
- engine/src/manager/timemanager.cpp
- engine/src/uci/crazyara.cpp
Allows a safe stopping of the search thread.
Locking a mutex from the main thread and releasing it in a different thread causes problems in Windows ("Unlock of unowned mutex"). Therefore, we need to use a condition variable and a mutex here.
Reference: https://github.com/dmfrodrigues/GraphViewerCpp/issues/16
Related:
* https://github.com/QueensGambit/CrazyAra/pull/167
* #81
> Stoppable search thread

- engine/CMakeLists.txt
Updates the OpenSpiel dependency which updates abseil-cpp to (hopefully) fix the continuous integration test for Stratego. For the newer abseil-cpp version new files are added to  `open_spiel_abseil_files` in CMakeLists.txt.
> Update OpenSpiel dependency

- engine/src/searchthread.cpp
This PR now checks for is_terminal() directly after creating a new node and sets the nodeBackup type accordingly.
```
./cutechess-cli -variant standard -openings file=chess.epd format=epd -pgnout fix_terminal_30ms.pgn -resign movecount=5 score=600 -draw movenumber=30 movecount=4 score=20 -concurrency 1 -engine name=ClassicAra-fixed-terminal cmd=./ClassicAra_fixed_terminal dir=/data/SL proto=uci -engine name=ClassicAra-master cmd=./ClassicAra_master dir=/data/SL proto=uci -each option.Fixed_Movetime=30 option.First_Device_ID=7 tc=40/6000+21 -games 2 -rounds 500 -repeat
```
```python
Score of ClassicAra-fixed-terminal vs ClassicAra-master: 403 - 307 - 166  [0.555] 876
Elo difference: 38.2 +/- 20.8, LOS: 100.0 %, DrawRatio: 18.9 %
Finished match
```
> Check for is_terminal() directly after creating a new node

- DeepCrazyhouse/configs/main_config.py
- DeepCrazyhouse/src/domain/variants/classical_chess/v3/input_representation.py
- DeepCrazyhouse/src/domain/variants/constants.py
- DeepCrazyhouse/src/domain/variants/crazyhouse/v3/input_representation.py
- DeepCrazyhouse/src/domain/variants/input_representation.py
- DeepCrazyhouse/src/domain/variants/lichess/input_representation.py
- DeepCrazyhouse/src/domain/variants/lichess/v3/input_representation.py
- engine/src/environments/chess_related/inputrepresentation.cpp
- engine/tests/tests.cpp
This PR adds the Lichess input representation v3 for MultiAra
This can be used as an ablation study to other paper: "Representation Matters: The Game of Chess Poses a Challenge to Vision Transformers".
It was tested so far only for the chess variant atomic and showed superior performance.
> Lichess inputs v3 with tests, cpp and python implementation

- DeepCrazyhouse/src/domain/variants/classical_chess/v2/input_representation.py
- DeepCrazyhouse/src/domain/variants/classical_chess/v3/input_representation.py
- engine/src/uci/crazyara.cpp
- engine/src/uci/crazyara.h
- engine/tests/tests.cpp
+ Fixes python input representation for 960 variants.
+ Adds unit test for input planes
+ Removes is960 from CrazyAra class
> Fix python input representation for 960

- DeepCrazyhouse/configs/train_config.py
- DeepCrazyhouse/src/training/train_cli.py
- DeepCrazyhouse/src/training/train_cli_util.py
This PR allows overwriting all configuration in `train_config.py` via command-line arguments.
The info-strings are being parsed as help information and all the cmd-line arguments when running the script are exported as well.
> Train config command liner parser

- engine/src/agents/agent.cpp
- engine/src/agents/agent.h
- engine/src/agents/mctsagent.cpp
- engine/src/agents/mctsagent.h
- engine/src/agents/rawnetagent.cpp
- engine/src/agents/rawnetagent.h
- engine/src/nn/neuralnetapi.cpp
- engine/src/nn/neuralnetapiuser.cpp
- engine/src/nn/neuralnetapiuser.h
- engine/src/searchthread.cpp
- engine/src/searchthread.h
- engine/src/uci/crazyara.cpp
- engine/src/uci/crazyara.h
- engine/src/uci/optionsuci.cpp
This PR fixes some problems from #216 .
* It fixes the RawNetAgent and compile bugs for RL mode.
* Change ordering of netBatchesVector (threads go first now)
* Use raw pointers in NeuralNetAPIUser now to resolve ownership problem
* Remove create_new_net_batches
* Add fill_nn_vectors()
* Add fill_single_nn_vector()
* [Make UCI-Option Nodes_Limit available in RL mode](https://github.com/QueensGambit/CrazyAra/commit/7eeb19ba3c3f2e2acbea1b48ba3268d6b45ad6b2)
Moreover, the neural network can also be loaded as previously without an additional subdirectory if no phases are used.
> MoE MCTS fixes

- DeepCrazyhouse/src/training/trainer_agent_pytorch.py
- engine/src/nn/neuralnetapiuser.cpp
- engine/src/nn/neuralnetapiuser.h
- engine/src/rl/rl_loop.py
- engine/src/rl/rl_training.py
- engine/src/rl/selfplay.cpp
- engine/src/rl/selfplay.h
- engine/src/rl/traindataexporter.cpp
- engine/src/rl/traindataexporter.h
- engine/src/uci/crazyara.cpp
This PR adds missing functionality for self play and fixes conflicts after the MoE update.
However, MoE itself is not supported yet.
> RL pytorch fix

- engine/CMakeLists.txt
- engine/src/environments/chess_related/chessbatchstream.cpp
- engine/src/environments/chess_related/chessbatchstream.h
- engine/src/nn/tensorrtapi.cpp
- engine/src/nn/tensorrtapi.h
This PR updates the TensorrtAPI to TensorRT 10.
* delete retrieve_indices_by_name()
* add member SampleUniquePtr<IRuntime> runtime
* replace getBindingDimensions() by getTensorShape()
* replace setBindingDimensions() by setInputShape()
* add link_libraries(stdc++fs) to CMakeLists.txt
* add include_directories("$ENV{TENSORRT_PATH}/samples/") to CMakeLists.txt
Unfortunately, TensorRT 10 is no longer working on older GPUs like GTX 1080ti.
> Update TensorrtAPI to TensorRT 10
