DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
crazyara.py

Tested from TC's 40/60s, 40/30s, 40/15s and 40/5s without time forfeit.
This PR also include other modifications such as:
- Added use_q_values option default is set to yes
-    playouts update stats is now set to number of threads
and others.

Added TC with period like 40/60

---

crazyara.py

To make it consistent with the remaining of the project, also to remove globals and to make fixing pylint errors easier

Make the main a class

---

DeepCrazyhouse/src/domain/abstract_cls/abs_agent.py
DeepCrazyhouse/src/domain/abstract_cls/abs_game_state.py
DeepCrazyhouse/src/domain/agent/player/MCTSAgent.py
DeepCrazyhouse/src/domain/agent/player/RawNetAgent.py
DeepCrazyhouse/src/domain/crazyhouse/GameState.py

implement ABC

---

DeepCrazyhouse/src/training/trainer_agent.py
crazyara.py

The code is much cleaner right now, I hope also slightly faster. I think next I'll do some refactoring but I'll take a small break from it first 
One thing - It's better to use specific error handling try-except block, but if you really  want to catch all its better to use `except Exception` instead of bare `except` since it excludes `KeyboardInterrupt`,  `SystemExit` and `GeneratorExit`, that you don't want to catch most of times

Final cleaning - reformatting(for now)

---

DeepCrazyhouse/src/domain/agent/player/alpha_beta_agent.py
DeepCrazyhouse/src/domain/agent/player/mcts_agent.py
DeepCrazyhouse/src/domain/crazyhouse/input_representation.py
DeepCrazyhouse/src/domain/crazyhouse/plane_policy_representation.py
DeepCrazyhouse/src/domain/neural_net/architectures/rise_builder_util.py
DeepCrazyhouse/src/domain/util.py
crazyara.py

Importing order, remove else after returns, few typos fixes, few other cleanings

Triial clean-ups

---

DeepCrazyhouse/src/domain/agent/player/mcts_agent.py
crazyara.py

title. 
The bug fixed was a one on enhance_checks that checked the board from a previous depth causing a crash.
This might need some tweaking

new optional parameter enhance_captures implementation and fix a bug

---

engine/src/agents/agent.cpp
engine/src/agents/agent.h
engine/src/agents/mctsagent.cpp
engine/src/agents/mctsagent.h
engine/src/boardstate.cpp
engine/src/boardstate.h
engine/src/crazyara.cpp
engine/src/crazyara.h
engine/src/manager/treemanager.h
engine/src/node.cpp
engine/src/node.h
engine/src/pommermanstate.cpp
engine/src/pommermanstate.h
engine/src/searchthread.cpp
engine/src/searchthread.h
engine/src/state.h
engine/src/stateobj.h

This PR changes the state interface into a **curiously recurring template pattern [(CRTP)](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern)** to reduce the amount of virtual function calls and to resolve polymorphism at compile time.

CRTP State Interface

---

engine/src/node.cpp

* sets custom terminal value correctly
* print actual Q-Values without clamping them

Added missing custom terminal value initialization

---

engine/src/agents/mctsagent.cpp
engine/src/evalinfo.cpp
engine/src/evalinfo.h
engine/src/manager/threadmanager.cpp
engine/src/manager/threadmanager.h
engine/src/node.cpp
engine/src/node.h

Allows setting of Q-Value Weight via UCI-option.

Enabled Q-Value Weight

---

engine/src/constants.h
engine/src/evalinfo.cpp
engine/src/node.cpp
engine/src/node.h
engine/src/nodedata.h
engine/src/searchthread.cpp

Added functionality for table base solver:
* Added `MCTS_TB_SUPPORT`
* Removed `SOLVED_` prefix
* Added `MCTS_SINGLE_PLAYER`
* Added `mark_as_tb_loss()`, `mark_as_tb_draw()`, `mark_as_tb_win()`
* Added `solve_tb_win()`, `solve_tb_draw()`, `solve_tb_loss()`

Tablebase Solver

---

engine/src/agents/mctsagent.cpp
engine/src/constants.h
engine/src/searchthread.cpp
engine/src/searchthread.h

Added partial return for epsilon-greedy search.
This allows generating disconnected trajectories.

Partial return

---

engine/src/rl/Dockerfile
engine/src/rl/README.md

+ add checkouts to release tags in Dockerfile to ensure that binary is building
+ added USE_RL flag to Dockerfile 
+ added rename of configs files to Dockerfile
+ update README.md accordingly

Dockerfile

---

engine/src/rl/rl_loop.py

- Used the `rtpt` library to update the process name
- Used the same schema to rename the binary
- Included new initals variable as command line argument
- This way other people on a cluster can see who is using the GPU's

Change process and binary name

---

engine/src/nn/mxnetapi.cpp
engine/src/nn/mxnetapi.h
engine/src/nn/neuralnetapi.cpp
engine/src/nn/neuralnetapi.h
engine/src/nn/neuralnetapiuser.cpp
engine/src/nn/tensorrtapi.cpp
engine/src/nn/tensorrtapi.h
engine/src/nn/torchapi.cpp
engine/src/nn/torchapi.h
engine/src/uci/crazyara.cpp

This PR adds a runtime validation of the loaded neural network architecture by comparing with the pre-defined environment constants.
* NeuralNetDesign
* validate_neural_network()
* init_nn_design()
* nn_api::Shape

Validation of dynamically loaded NN-architecture

---

engine/src/nn/mxnetapi.cpp
engine/src/nn/neuralnetapi.cpp
engine/src/nn/neuralnetapi.h
engine/src/nn/neuralnetapiuser.cpp
engine/src/nn/tensorrtapi.cpp
engine/src/nn/torchapi.cpp
engine/src/searchthread.cpp
engine/src/searchthread.h

This PR uses the dynamically loaded input shape and auxiliary outputs to allocate memory and for inference.
The previous assert conditions are now optionally to compare the neural network input shape with a pre-defined default neural network design.

Dynamic Neural Network Architecture

---

engine/src/agents/config/searchlimits.cpp
engine/src/agents/config/searchlimits.h
engine/src/manager/timemanager.cpp
engine/src/uci/crazyara.cpp
engine/src/uci/crazyara.h

* added `CrazyAra::prepare_search_config_structs()`
* added `searchLimits::init_new_search()`
This makes sure that the searchLimits are correctly set for RL.

SearchLimit configuration

---

DeepCrazyhouse/src/training/train_cnn.ipynb
DeepCrazyhouse/src/training/trainer_agent.py
DeepCrazyhouse/src/training/trainer_agent_mxnet.py
engine/src/rl/rl_training.py

* Changed `nb_epochs` parameter to `nb_training_epochs` in `train_cnn`
* Return all `losses` and `accuracies` of the best model epoch after training has finished.
* Added a print out in `train_cnn` of the losses and accuracies of the best model

Supervised Learning return params

---

engine/src/agents/config/searchlimits.cpp
engine/src/agents/config/searchlimits.h
engine/src/manager/threadmanager.cpp
engine/src/node.cpp
engine/src/searchthread.cpp
engine/src/uci/optionsuci.cpp

Added UCI-Option `"Nodes_Limit"`:
* defines a maximum number of nodes to remain in RAM limit
* updated "Model_Directory_Contender" for MODE_CHESS, MODE_XIANGQI

 UCI-Option "Nodes_Limit"

---

engine/src/evalinfo.cpp
engine/src/manager/threadmanager.cpp
engine/src/node.cpp
engine/src/node.h
engine/src/searchthread.cpp
engine/src/uci/customlogger.cpp
engine/src/uci/customlogger.h

* renamed `get_nodes()` into `get_node_count()`
* replaced `get_node_count(Node*)` by `get_nodes()`
* replaced `_Ios_Openmode` with `ios_base::openmode` ( 🛠️ fixes compilation issue on Mac)

NPS Measure Refactoring

---

engine/src/agents/mctsagent.cpp
engine/src/constants.h
engine/src/environments/chess_related/boardstate.cpp
engine/src/node.cpp
engine/src/searchthread.cpp
engine/src/searchthread.h
engine/tests/tests.cpp

* fixed overwrite of `NodeType` for tabelbase nodes
This should fix the blunder as seen in: https://tcec-chess.com/#div=q43t&game=293&season=21
* added Unit-Test

Syzygy probe fix

---

engine/src/agents/mctsagent.cpp
engine/src/constants.h
engine/src/node.cpp
engine/src/node.h
engine/src/searchthread.cpp
engine/src/searchthread.h

* fix potential crash
* avoid overwriting NodeData for tablebase nodes
* delete inCheck from Node

Fix potential crash

---

AUTHORS

This PR adds detailed information about authors, supervisors, contributors and supporters.

Author information

---

engine/src/rl/Dockerfile

This PR adds debugging utilities to the Dockerfile.

Docker debug utilities

---

engine/src/agents/mctsagent.cpp
engine/src/agents/rawnetagent.cpp
engine/src/constants.h
engine/src/environments/chess_related/boardstate.cpp
engine/src/environments/chess_related/boardstate.h
engine/src/environments/chess_related/chessbatchstream.cpp
engine/src/environments/chess_related/inputrepresentation.cpp
engine/src/environments/chess_related/inputrepresentation.h
engine/src/nn/tensorrtapi.cpp
engine/src/nn/tensorrtapi.h
engine/src/searchthread.cpp
engine/src/state.h
engine/tests/tests.cpp

* removed `legalActions` again from `get_state_planes() `
* increased version to 0.9.4
* added `is_terminal()` for `MCTS_TB_SUPPORT=false`
* improved debug info messages for TensorRT `retrieve_indices_by_name()`

Release 0.9.4

---

engine/src/rl/binaryio.py
engine/src/rl/rl_loop.py

Reverts QueensGambit/CrazyAra#130

Revert "RL Logging: Found tablebases and Configs"

---

.github/workflows/build.yml
.gitmodules

add blaze subproject
* this should make CI faster and simplify the installation process

3rdParty Blaze Dependency

---

.github/workflows/variants.yml
README.md
engine/src/environments/fairy_state/fairystate.cpp
engine/src/environments/fairy_state/fairystate.h
engine/src/environments/open_spiel/openspielstate.cpp
engine/src/environments/open_spiel/openspielstate.h
engine/tests/tests.h

Added CI to build tests for variants
- ClassicAra
- MultiAra
- XiangqiAra
CI is only run on PRs to master and not on commits to master.

CI for Variants

---

engine/CMakeLists.txt
engine/src/environments/chess_related/boardstate.cpp
engine/src/environments/chess_related/boardstate.h
engine/src/environments/chess_related/chessbatchstream.cpp
engine/src/environments/fairy_state/fairystate.h
engine/src/environments/open_spiel/openspielstate.cpp
engine/src/environments/open_spiel/openspielstate.h
engine/src/environments/stratego_related/strategostate.h
engine/src/rl/selfplay.cpp
engine/src/state.h
engine/src/uci/crazyara.cpp
engine/src/uci/crazyara.h
engine/src/uci/main.cpp
engine/src/uci/optionsuci.cpp
engine/src/uci/optionsuci.h
engine/tests/tests.cpp
engine/tests/tests.h

This PR allows defining the **availableVariants** and **StartFENs** within the state interface.

State variants

---

engine/src/nn/tensorrtapi.cpp
engine/src/nn/tensorrtapi.h

This PR udpates the deprecated TensorRT API functions.

TensorRT API Update

---

engine/src/evalinfo.cpp
engine/src/node.cpp

* Fixes print log of MCTS solver for `MCTS_SINGLE_PLAYER`
* Fixes setting `evalInfo.bestMoveQ` for solver terminals

Update MCTS solver for MCTS_SINGLE_PLAYER

---

DeepCrazyhouse/src/training/README.md
engine/src/rl/Dockerfile
engine/src/rl/README.md

This PR allows the generation and analysis of core dumps in the CrazyAra docker container.
The README files are also updated accordingly.

Docker core dumps

---

DeepCrazyhouse/src/domain/neural_net/architectures/pytorch/alpha_vile.py
DeepCrazyhouse/src/preprocessing/pgn_converter_util.py
DeepCrazyhouse/src/preprocessing/pgn_to_planes_converter.py
DeepCrazyhouse/src/preprocessing/puzzles/puzzle_to_planes_converter.py
DeepCrazyhouse/src/training/train_cli.py
DeepCrazyhouse/src/training/train_cli_util.py
DeepCrazyhouse/src/training/trainer_agent_pytorch.py

This PR adds a command line script that allows generating the plane representation for lichess puzzles.

Lichess Puzzles
